# src/configs/system/logvmamba_system.yaml

_target_: src.systems.logvmamba_system.LogVMambaSystem

model_cfg:
  # 指向工厂函数而非类本身
  _target_: src.models.logvmamba.get_umamba_enc_dc_k1_3d_from_plans
  
  # 工厂函数定义的参数
  num_input_channels: 3
  num_output_channels: 1    # 分割类别数
#  num_classes_clf: 2        # 分类类别数 (改造后的新增参数)
  depth_mode: "even"
  conv_mode: "full"
  expand: 2
  deep_supervision: True

learning_rate: 1e-6
loss_type: "bce"   # 可选: bce | focal | dice | bce_dice | tversky | asymmetric | asymmetric_bce | weighted_bce | iou | hinge
bce_pos_weight: 1